### ISSUE TITLE
error message could be improved

### ISSUE THREAD

**Issue by rpruim** [treytipton4/fuzzybunnies#47]
https://github.com/treytipton4/fuzzybunnies/blob/fca84d9793f6d93f1c701ee8cf86e45cf80b7e11/R/df_apply.R#L24

You don't have an argument named `dataset` and you are testing that it is a **data frame**, not a data set.

**Comment by treytipton4** [comment]
I took your other advice and used the stopifnot() method. Now, if the function gets a dataframe, it returns an error message like so: Error in df_apply(x, round) : is.data.frame(.data) is not TRUE

If you still want a more descriptive error message (a written one), let me know...

**Comment by rpruim** [comment]
Your message looks good, but it focuses on implementation.

Another possible style would be something like: `.data must be a data frame.`
