### ISSUE TITLE
No need to create "loose" vectors in you example

### ISSUE THREAD

**Issue by rpruim** [treytipton4/fuzzybunnies#48]
https://github.com/treytipton4/fuzzybunnies/blob/fca84d9793f6d93f1c701ee8cf86e45cf80b7e11/R/df_apply.R#L12

You can create vectors for columns directly in `data.frame()` or `dplyr::tibble()`.  This is cleaner as it doesn't put unnecessary things into the working environment.

**Comment by treytipton4** [comment]
fixed this in df_apply
