### ISSUE TITLE
Provide additional information about the function arguments

### ISSUE THREAD

**Issue by rpruim** [treytipton4/fuzzybunnies#49]
https://github.com/treytipton4/fuzzybunnies/blob/fca84d9793f6d93f1c701ee8cf86e45cf80b7e11/R/df_apply.R#L3

In particular, you should tell users:

* that `.data` needs to be a data frame.
* what sorts of functions (inputs and return values) `.filter()` and `.fun()` need to be.
* How `.fun()` is "applied".

**Comment by treytipton4** [comment]
updated parameter descriptions, should look better now... about to merge
