### ISSUE TITLE
The example for df_apply() only shows one simple application

### ISSUE THREAD

**Issue by rpruim** [treytipton4/fuzzybunnies#50]
It might be good to demonstrate the use of ... and perhaps a different filter function.  Think about the sorts of examples you would like to see if you were learning about this function for the first time.

**Comment by treytipton4** [comment]
Added an example for both: applied the str_trunc() function to a dataframe ... Looks like this:

xy_days_of_week <- data.frame(x = c(1,2,3,4,5,6,7), y = c('Sunday', Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'))

 df_apply(xy_days_of_week, str_trunc, is.character, width = 4)
